### ISSUE TITLE
The operation failed. Do you need any additional information?

### ISSUE THREAD

**Issue by abucc** [cucumber-pickle/tomarketCum#1]
FREE TO USE = Join us on t.me/cucumber_scripts
 before start please 'git pull' to update bot

[2024-10-31 09:26:48] total account : 1
[2024-10-31 09:26:48] total proxies detected : 1
[2024-10-31 09:26:48] use proxy : True
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "F:\workSpace\tomarketCum-master\bot.py", line 670, in <module>
    app.main()
  File "F:\workSpace\tomarketCum-master\bot.py", line 625, in main
    user = json.loads(parser["user"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python312\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 18 (char 17)

data.txt===query_id=&user=
token.json === {}
proxies.txt===http://127.0.0.1:7897

**Comment by abucc** [comment]
I found the issue: the data.txt file needs the complete token, not just the queryid and user.
